### ISSUE TITLE
Confirm the example/helloworld server-side render's bug

### ISSUE THREAD

**Issue by mis101bird** [jimmy319/universal-react-apollo#17]
After following the steps to start the example server, I found the url `http://localhost:3000/greeting/visitor2` shows the UI below.
![image](https://user-images.githubusercontent.com/8818527/86509875-ce23c080-be1d-11ea-8acf-e5252fb3a0e0.png)
But I think the correct wording should be `Hello visitor2: this is your first universal react apollo app`.

After check, I found the query don't execute in server side, instead, it execute in client side. However, the ssr is true by default when using `useQuery`. Do you have the same problem here?

**Comment by jimmy319** [comment]
Good catch! This issue happens due to this [Release](https://github.com/jimmy319/universal-react-apollo/releases/tag/v1.0.20). I had fixed it by [this commit](https://github.com/jimmy319/universal-react-apollo/commit/6f573e109aa35779d8cdea3d6ad5e91836f30b8d), you can try it again.

**Comment by mis101bird** [comment]
Cool~~It works! Thx
